### ISSUE TITLE
后端mock服务 启动不了

### ISSUE THREAD

**Issue by 66eagle** [wjkang/d2-admin-pm#9]
MacBook-Pro:d2-sql eagle$ cnpm start

> lazy-mock@1.0.0 start /www/d2-sql
> gulp nodemon

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/www/d2-sql/node_modules/_natives@1.1.6@natives/index.js:143:24)
    at Object.req [as require] (/www/d2-sql/node_modules/_natives@1.1.6@natives/index.js:55:10)
    at Object.<anonymous> (/www/d2-sql/node_modules/_graceful-fs@3.0.12@graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.require.extensions.<computed> [as .js] (/www/d2-sql/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lazy-mock@1.0.0 start: `gulp nodemon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lazy-mock@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eagle/.npm/_logs/2019-11-06T10_10_42_067Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm',
1 verbose cli   '--userconfig=/Users/eagle/.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--registry=https://r.npm.taobao.org',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle lazy-mock@1.0.0~prestart: lazy-mock@1.0.0
6 info lifecycle lazy-mock@1.0.0~start: lazy-mock@1.0.0
7 verbose lifecycle lazy-mock@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle lazy-mock@1.0.0~start: PATH: /usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/www/d2-sql/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/eagle/Library/Application Support/GoodSync:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/Ghostscript/bin:/opt/ImageMagick/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/git/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/eagle/Library/Application Support/GoodSync:/AIRSDK/bin:/Applications/MAMP/Library/bin:/AIRSDK/bin:/Applications/MAMP/Library/bin
9 verbose lifecycle lazy-mock@1.0.0~start: CWD: /www/d2-sql
10 silly lifecycle lazy-mock@1.0.0~start: Args: [ '-c', 'gulp nodemon' ]
11 silly lifecycle lazy-mock@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle lazy-mock@1.0.0~start: Failed to exec start script
13 verbose stack Error: lazy-mock@1.0.0 start: `gulp nodemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:209:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:209:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid lazy-mock@1.0.0
15 verbose cwd /www/d2-sql
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/eagle/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://r.npm.taobao.org" "start"
18 verbose node v12.10.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error lazy-mock@1.0.0 start: `gulp nodemon`
22 error Exit status 1
23 error Failed at the lazy-mock@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

啥问题呀。

**Comment by 66eagle** [comment]
我的的是 v6.10  node  ， macos 系统下

去node官网下载了，升级到，6.11版本， 稳定版本，

可以了。
